networks:
  default:
    external: true
    name: "traefik_default"

services:
  dev-aggy-webui:
    build:
      context: .
      dockerfile: dockerfile
    environment:
      - AGGY_API_URL=http://codehostapi.doze.dev
    labels:
      - "traefik.http.routers.aggydevwebui.rule=Host(`devaggy.doze.dev`)"
      - "traefik.http.routers.aggydevwebui.service=aggydevwebui"
      - "traefik.http.services.aggydevwebui.loadbalancer.server.port=80"
