services:
  test-blinder-db:
    image: "redis:latest"
    ports:
      - 6379

  test-blinder-shared:
    build:
      context: ./src/shared
      dockerfile: dockerfile.test
    environment:
      - REDIS_HOST=test-blinder-db
      - REDIS_PORT=6379
    depends_on:
      - test-blinder-db
