version: '3.8'

networks:
  default:
    external: true
    name: "traefik_default"

services:
  blinder-webui:
    build: ./src/webui
    ports:
      - "5000:5000"
    environment:
      - HOSTNAME=https://codehost.doze.dev
    labels:
      - "traefik.http.routers.codehost.rule=Host(`codehost.doze.dev`)"
      - "traefik.http.routers.codehost.service=codehost"
      - "traefik.http.services.codehost.loadbalancer.server.port=5000"
    depends_on:
      - blinder-db

  blinder-db:
    image: "redis:latest"
    ports:
      - "6379"
    volumes:
      - blinder-db:/data

  blinder-ingest:
    build: ./src/ingest
    depends_on:
      - blinder-db

volumes:
  blinder-db:
