# version: '3.8'

networks:
  default:
    external: true
    name: "traefik_default"

services:
  dev-blinder-db:
    image: "redis:latest"
    ports:
      - 7524:6379
    volumes:
      - dev-blinder-db:/data

  # # https://github.com/HenryQW/mercury-parser-api
  # dev-blinder-extract:
  #   image: wangqiru/mercury-parser-api
  #   ports:
  #     - 7525:3000

  # dev-blinder-ingest:
  #   build: ./src/ingest
  #   ports:
  #     - 7526:9001
  #   environment:
  #     - REDIS_HOST=dev-blinder-db
  #     - REDIS_PORT=6379
  #     - EXTRACT_HOST=dev-blinder-extract
  #     - EXTRACT_PORT=3000
  #     - INGEST_NUM_THREADS=4
  #   depends_on:
  #     - dev-blinder-db
  #     - dev-blinder-extract

  dev-blinder-api:
    build: ./src/api
    ports:
      - 7356:8000
    environment:
      - REDIS_HOST=dev-blinder-db
      - REDIS_PORT=6379
      - JWT_ALGORITHM=HS256
      - JWT_SECRET=429bceb2ab20f5785a4b609a725b0164be73a95d8ce04706ed8366cfe6ade896 # openssl rand -hex 32
    labels:
      - "traefik.http.routers.codehostapi.rule=Host(`codehostapi.doze.dev`)"
      - "traefik.http.routers.codehostapi.service=codehostapi"
      - "traefik.http.services.codehostapi.loadbalancer.server.port=8000"
    depends_on:
      - dev-blinder-db

volumes:
  dev-blinder-db:
