version: '3.8'
services:
  database:
    build: ./src/database
    ports:
      - "5432:5432"  # Expose if needed
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  webui:
    build: ./src/webui
    ports:
      - "5001:5000"
    depends_on:
      - database
    environment:
      - DB_HOST=database
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASS=postgres

volumes:
  dbdata:
