from config import config
from datetime import timedelta

SOURCES_TO_INGEST_KEY = "SOURCE-KEYS-TO-INGEST"
SOURCE_READ_INTERVAL_TIMEDELTA = timedelta(
    minutes=config.get("SOURCE_READ_INTERVAL_MINUTES")
)

SCORE_ESTIMATORS_TO_TRAIN_KEY = "SCORE-ESTIMATORS-TO-TRAIN"
SCORE_ESTIMATE_TRAINING_INTERVAL_TIMEDELTA = timedelta(
    hours=config.get("SCORE_ESTIMATE_TRAINING_INTERVAL_HOURS")
)

SCORE_ESTIMATORS_TO_INFER_KEY = "SCORE-ESTIMATORS-TO-INFER"
SCORE_ESTIMATE_INFERENCE_INTERVAL_TIMEDELTA = timedelta(
    hours=config.get("SCORE_ESTIMATE_TTL_HOURS")
)
