from config import config
from datetime import timedelta

SOURCES_TO_INGEST_QUE = "SOURCE-KEYS-TO-INGEST"
SOURCE_READ_INTERVAL_TIMEDELTA = timedelta(
    minutes=config.get("SOURCE_INGESTION_INTERVAL_MINUTES")
)

SCORE_ESTIMATORS_TO_TRAIN_QUE = "SCORE-ESTIMATOR-KEYS-TO-TRAIN"
SCORE_ESTIMATE_TRAINING_INTERVAL_TIMEDELTA = timedelta(
    hours=config.get("SCORE_ESTIMATE_TRAINING_INTERVAL_HOURS")
)

SCORE_ESTIMATORS_TO_INFER_QUE = "SCORE-ESTIMATOR-KEYS-TO-INFER"
SCORE_ESTIMATE_INFERENCE_INTERVAL_TIMEDELTA = timedelta(
    hours=config.get("SCORE_ESTIMATE_REFRESH_HOURS")
)
