services:
  test-blinder-db:
    image: valkey/valkey:7.2.5-alpine
    ports:
      - 6379

  test-blinder-api:
    build:
      context: .
      dockerfile: dockerfile.test
    environment:
      - DB_HOST=test-blinder-db
      - DB_PORT=6379
    depends_on:
      - test-blinder-db
