FROM python:3.11-alpine as aggy-api
WORKDIR /src

ENV TZ=America/New_York

RUN apk add --no-cache libpq

COPY requirements.txt .

RUN apk add --no-cache --virtual .build-deps gcc musl-dev libpq-dev \
    && pip install --no-cache-dir -r requirements.txt \
    && apk del .build-deps

COPY . /src/api

EXPOSE 8000

CMD pytest -x /src/api/tests/
