FROM python:3.11-alpine as blinder-api
WORKDIR /src

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . /src/api

EXPOSE 8000

CMD pytest /src/api/tests/ --cov=/src/api --cov-report=xml:/coverage/coverage.xml && ls -la /coverage
