FROM apache/airflow:slim-latest-python3.9 as aggy-api

# set airflow dags folder
ENV AIRFLOW__CORE__DAGS_FOLDER=/src/api/dags

WORKDIR /src

ENV TZ=America/New_York

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . /src/api

ENV PYTHONPATH="/src/api:${PYTHONPATH}"


# Set version
ARG BUILD_VERSION=0.0.0-beta
ENV BUILD_VERSION=${BUILD_VERSION}

USER root

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

USER airflow

EXPOSE 8000
EXPOSE 8080

ENTRYPOINT ["/entrypoint.sh"]
