FROM python:3.11-alpine as aggy-api
WORKDIR /src

ENV TZ=America/New_York

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . /src/api

# Set version
ARG BUILD_VERSION=0.0.0-beta
ENV BUILD_VERSION=${BUILD_VERSION}


EXPOSE 8000

CMD python /src/api/main.py
