FROM apache/airflow:2.6.3-python3.11 as aggy-api

# set airflow dags folder
ENV AIRFLOW__CORE__DAGS_FOLDER=/src/api/dags

WORKDIR /src

ENV TZ=America/New_York

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . /src/api

# Set version
ARG BUILD_VERSION=0.0.0-beta
ENV BUILD_VERSION=${BUILD_VERSION}


EXPOSE 8000
EXPOSE 8080

CMD python /src/api/main.py
