services:
  test-aggy-db:
    image: valkey/valkey:8.0.0-alpine
    ports:
      - 6379

  test-aggy-rss-bridge:
    image: rssbridge/rss-bridge:latest
    restart: unless-stopped
    ports:
      - 80

  test-aggy-api:
    build:
      context: .
      dockerfile: dockerfile.test
    environment:
      - DB_HOST=test-aggy-db
      - DB_PORT=6379
      - RSS_BRIDGE_HOST=dev-aggy-rss-bridge
      - RSS_BRIDGE_PORT=80
      - JWT_ALGORITHM=HS256
      - JWT_SECRET=429bceb2ab20f5785a4b609a725b0164be73a95d8ce04706ed8366cfe6ade896 # openssl rand -hex 32
    depends_on:
      - test-aggy-db
      - test-aggy-rss-bridge
