networks:
  default:
    external: true
    name: "traefik_default"

services:
  dev-aggy-db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=aggy
      - POSTGRES_PASSWORD=aggy
      - POSTGRES_DB=aggy
    ports:
      - 5432
    volumes:
      - "dev-aggy-db-data:/var/lib/postgresql/data"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U aggy -d aggy"]
      interval: 5s
      timeout: 5s
      retries: 10

  dev-aggy-flyway:
    image: flyway/flyway:10-alpine
    command: -url=jdbc:postgresql://dev-aggy-db:5432/aggy -user=aggy -password=aggy -connectRetries=30 migrate
    volumes:
      - "./db/migrations:/flyway/sql"
    depends_on:
      dev-aggy-db:
        condition: service_healthy

  dev-aggy-pgadmin:
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@aggy.local
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_CONFIG_SERVER_MODE=False
    ports:
      - 80
    volumes:
      - "dev-aggy-pgadmin-data:/var/lib/pgadmin"
    depends_on:
      - dev-aggy-db

  # https://github.com/HenryQW/mercury-parser-api
  dev-aggy-extract:
    image: wangqiru/mercury-parser-api
    ports:
      - 3000

  dev-aggy-rss-bridge:
    image: rssbridge/rss-bridge:latest
    restart: unless-stopped
    ports:
      - 80

  dev-aggy-ollama:
    container_name: dev-aggy-ollama
    image: ollama/ollama:latest
    restart: unless-stopped
    ports:
      - 11434
    volumes:
      - "dev-aggy-ollama-data:/root/.ollama"

  dev-aggy-api:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - 8000
    environment:
      - DB_HOST=dev-aggy-db
      - DB_PORT=5432
      - DB_USER=aggy
      - DB_PASSWORD=aggy
      - DB_NAME=aggy
      - RSS_BRIDGE_HOST=dev-aggy-rss-bridge
      - RSS_BRIDGE_PORT=80
      - EXTRACT_HOST=dev-aggy-extract
      - EXTRACT_PORT=3000
      - OLLAMA_HOST=dev-aggy-ollama
      - OLLAMA_PORT=11434
      - OLLAMA_EMBEDDING_MODEL=mxbai-embed-large:latest
      - JWT_ALGORITHM=HS256
      - JWT_SECRET=429bceb2ab20f5785a4b609a725b0164be73a95d8ce04706ed8366cfe6ade896 # openssl rand -hex 32
    labels:
      - "traefik.http.routers.codehostapi.rule=Host(`codehostapi.doze.dev`)"
      - "traefik.http.routers.codehostapi.service=codehostapi"
      - "traefik.http.services.codehostapi.loadbalancer.server.port=8000"
    depends_on:
      dev-aggy-db:
        condition: service_healthy
      dev-aggy-flyway:
        condition: service_completed_successfully
      dev-aggy-rss-bridge:
        condition: service_started


volumes:
  dev-aggy-ollama-data:
  dev-aggy-db-data:
  dev-aggy-pgadmin-data:
