name: Python application test with Redis

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        ports:
          - 6379:6379
        options: --name test_redis --network-alias redis

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install pytest docker redis
    - name: Run tests
      env:
        REDIS_HOST: redis  # Uses the service container's network alias
        REDIS_PORT: 6379
        PYTEST_RUNTIME_TYPE: ci  # Indicate that tests are running in CI environment
        PYTEST_REDIS_DOCKER_NETWORK: bridge  # Use the default Docker bridge network
      run: |
        pytest
